### ISSUE TITLE
clone_wp_site.py: "No such file or directory" error

### ISSUE THREAD

**Issue by cvn** [opalstack/opalstack-python#6]
Hi, I'm getting an error using clone_wp_site.py to clone an app locally.

```pytb
Traceback (most recent call last):
  ...
  File "clone_mysite.py", line 156, in main
    mariatool_remote.import_remote_db(sshrunner, sql_filepath_remote)
  ...
RuntimeError: ... /home/myuser/mysite.sql: No such file or directory
```

<details>
<summary>Full log</summary>

```pytb
[myuser@opal1 ~]$ python3 clone_mysite.py 
2022-09-29 15:21:00 : INFO  : Retrieving webserver information for opal1.opalstack.com
2022-09-29 15:21:01 : INFO  : Retrieving existing osuser myuser
2022-09-29 15:21:02 : INFO  : Creating domain test.mysite.com
2022-09-29 15:21:13 : INFO  : Creating application mysite
2022-09-29 15:21:35 : INFO  : Creating site mysite
2022-09-29 15:21:41 : INFO  : Retrieving database configurations
2022-09-29 15:21:45 : INFO  : Exporting database
2022-09-29 15:21:46 : INFO  : Copying files
2022-09-29 15:21:49 : INFO  : Copying database content
2022-09-29 15:21:49 : INFO  : Importing database
Traceback (most recent call last):
  File "clone_mysite.py", line 170, in <module>
    main(args)
  File "clone_mysite.py", line 156, in main
    mariatool_remote.import_remote_db(sshrunner, sql_filepath_remote)
  File "/usr/local/lib/python3.6/site-packages/opalstack/util.py", line 361, in import_remote_db
    sshrunner.run_ssh(cmd)
  File "/usr/local/lib/python3.6/site-packages/opalstack/util.py", line 259, in run_ssh
    return self.run_passbased_ssh(remote_cmd, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/opalstack/util.py", line 144, in run_passbased_ssh
    return self.run_via_sshpass(prelude + [remote_cmd], *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/opalstack/util.py", line 133, in run_via_sshpass
    return run(prelude + cmd, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/opalstack/util.py", line 23, in run
    raise RuntimeError(f'Command "{cmd}" exited with status {p.returncode}. Stderr: {stderr}')
RuntimeError: Command "['sshpass', '-f', 'myuser.sshpass', '/usr/bin/ssh', '-q', '-o', 'PasswordAuthentication=yes', '-o', 'PubkeyAuthentication=no', '-o', 'StrictHostKeyChecking=no', '[myuser@opal1.opalstack.com](mailto:myuser@opal1.opalstack.com)', 'mysql --defaults-extra-file=/home/myuser/mysite.sqlpasswd -u mysite_12345678 mysite_12345678 < /home/myuser/mysite.sql']" exited with status 1. Stderr: bash: /home/myuser/mysite.sql: No such file or directory
```

</details>

When src and dst are the same server, line 152 copies the exported sql file to itself, line 153 deletes it, and then line 156 fails when it tries to import the missing file.

https://github.com/opalstack/opalstack-python/blob/13642f1e74de74daa38e8c5ed97cfe432494eeee/examples/clone_wp_site.py#L151-L157

**Comment by yqdv** [comment]
Similarly to #8, my apologies for oversight and for any trouble caused.
Development of this script was performed across two separate servers, and so I missed this case.
Fix merged and will be included in v1.0.1.
